### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by UrbanDavid** [rsmuc/health_monitoring_plugins#21]
Good morning.
I installed your plugin for idrac but I have only phyton3 installed.

I tried to use it but I have error message: 

Traceback (most recent call last):
  File "/usr/local/bin/check_snmp_idrac.py", line 104, in <module>
    idrac.process_temperature_sensors(helper, sess)
  File "/usr/local/lib/python3.6/site-packages/health_monitoring_plugins/idrac.py", line 324, in process_temperature_sensors
    helper.add_metric(label=snmp_result_temp_sensor_names[i] + " -Celsius-",
TypeError: can't concat str to bytes

Is it possible to run it under phyton 3?

**Comment by rsmuc** [comment]
Hi David,
sorry the plugins will only work with Python 2.
We are currently working on a version for Python 3 but it will take some time until we release them.
