### ISSUE TITLE
netsnmp.Session error

### ISSUE THREAD

**Issue by UrbanDavid** [rsmuc/health_monitoring_plugins#22]
Dear, 
I installed a new Icinga satellite. And I installed our plugin via pip. I am using centos 8 stream edition. I installed python 2,7 and I have this error message.  I have installed 3 other servers with this plugin and working well.

[root@xx]# ./check_snmp_idrac.py
Traceback (most recent call last):
  File "./check_snmp_idrac.py", line 21, in <module>
    import health_monitoring_plugins.idrac
  File "/usr/lib/python2.7/site-packages/health_monitoring_plugins/__init__.py", line 139, in <module>
    class SnmpSession(netsnmp.Session):
AttributeError: 'module' object has no attribute 'Session'

**Comment by UrbanDavid** [comment]
Sorry, I uninstall module netsnmp-py and all working well.
